name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: fwal/setup-swift@v2
      with:
        swift-version: '6.0.0'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
